name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Build the project
        run: uv build
      - name: Publish to PyPi
        run: uv publish
